// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz2W7pkTa34OroRI4hAxBAt5tIgLVujAQ',
    appId: '1:382588611844:web:5c6d969f354104e443f451',
    messagingSenderId: '382588611844',
    projectId: 'eat-wise-app-db',
    authDomain: 'eat-wise-app-db.firebaseapp.com',
    storageBucket: 'eat-wise-app-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQUZHUj6OCSwYdHZIUSVPtCvGSOdqnRLE',
    appId: '1:382588611844:android:519208dd197c88ee43f451',
    messagingSenderId: '382588611844',
    projectId: 'eat-wise-app-db',
    storageBucket: 'eat-wise-app-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP_mpAu6pDNwM7_EW_GtSLpYwBZCGaRC8',
    appId: '1:382588611844:ios:ed8cf33a15bbcfe043f451',
    messagingSenderId: '382588611844',
    projectId: 'eat-wise-app-db',
    storageBucket: 'eat-wise-app-db.firebasestorage.app',
    iosBundleId: 'com.example.eatWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP_mpAu6pDNwM7_EW_GtSLpYwBZCGaRC8',
    appId: '1:382588611844:ios:ed8cf33a15bbcfe043f451',
    messagingSenderId: '382588611844',
    projectId: 'eat-wise-app-db',
    storageBucket: 'eat-wise-app-db.firebasestorage.app',
    iosBundleId: 'com.example.eatWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz2W7pkTa34OroRI4hAxBAt5tIgLVujAQ',
    appId: '1:382588611844:web:50ea12c65d66250143f451',
    messagingSenderId: '382588611844',
    projectId: 'eat-wise-app-db',
    authDomain: 'eat-wise-app-db.firebaseapp.com',
    storageBucket: 'eat-wise-app-db.firebasestorage.app',
  );
}
